---
title: Locness
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  stuff:
    title: Stuff
    output: true
  uploads:
    title: Uploads
    output: true
intro: |
  Welcome to my site v2.0 !<br>
  I'm still a "young boy passionated about computers", as I wrote before.<br>
theme: jekyll-theme-cayman
