---
title: Locness
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  stuff:
    title: Stuff
    output: true
  uploads:
    title: Uploads
    output: true
intro: |
  Welcome to my website!<br>
  Nothing much to say, except check my stuff below!
theme: jekyll-theme-cayman
