---
title: Locness3.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  stuff:
    title: Stuff
    output: true
  uploads:
    title: Uploads
    output: true
intro: |-
  Welcome to my site v2.0 !<br>
  I'm still a "young boy passionated about computers", as I wrote before.<br>
  <h1>My stuff</h1>

theme: jekyll-theme-cayman