---
title: Locness3.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  stuff:
    title: Stuff
    output: true
  uploads:
    title: Uploads
    output: true
intro: "Welcome to my site v2.0 !  \nI'm now using [Jekyll](http://jekyllrb.com) and
  [SiteLeaf](http://siteleaf.com).\nI'm still a \"young boy passionated about computers\",
  as I wrote before.\nFind my stuff here."
